VIENNA-Advantage-ERP-CRM/VA009_PaymentManagement

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Handle Culture and Balance filed not showing correct data and some other issues in Payment form.
=> Handle Culture.

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
=> Handle UI in Manual Payment

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
handling dates and Bank button issues
=> PaymentForm issue

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs
Handled writeoff amount and discount amount
=> Handled signs of Amounts

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
=> handled Dates

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
=> checkdate issue

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Fix the issue of dispose the elements of Payment Form after usage completed!
=> Trn18 payment form 06 10 2020

ViennaAdvantage/Areas/VA009/Contents/VA009_PaymentFrm.css, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Handled - JID_1554 in Payment form.
=> Handled - JID_1554 in Payment form.

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Resolved JID_1907 in Payment form.
=> Resolved JID_1907 in Payment form.

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs
Handle OverUnder Amount in case of APP
=> Handle OverUnder Amount in case of APP

ViennaAdvantage/Areas/VA009/Controllers/PayController.cs, ViennaAdvantage/Areas/VA009/Models/PayModel.cs, ViennaAdvantage/Areas/VA009/Scripts/model/callouts.js
PayAmount issue in Payment window for Prepay Order.
=> PayAmount issue in Payment window for Prepay Order.

ViennaAdvantage/Areas/VA009/Scripts/model/callouts.js
QA - Clear weekday and disable schedule tab
=> Dev pay mngt

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
When change the CheckDate in the grid, same value is not updating on the Check Date field on the above form in CheckPayables PopUp window - Issue fixed.
=> Va009 payment management 24 may 2021

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
1. Select All check box must be false after Creation of Payment.
2. Handled Payment form Design on refresh with multiple tabs.
=> 1. Select All check box must be false after Creation of Payment.

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Message entry searchKey length issue on PaymentForm.
=> Message entry searchKey length issue on PaymentForm.

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
DueDate issue on Split Payment grid is fixed!
=> DueDate issue on Split Payment grid is fixed!

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineForm.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs
Type Error fixed to Execute the Query when Create the Batch Lines.
=> Type Error fixed to Execute the Query when Create the Batch Lines.

ViennaAdvantage/Areas/VA009/Controllers/PaymentController.cs, ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js, ViennaAdvantage/Areas/VA009/Scripts/model/callouts.js, ViennaAdvantageSvc/Model/MVA009Batch.cs, ViennaAdvantageSvc/Model/X_VA009_Batch.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs, ViennaAdvantageSvc/Process/VA009_Generate_Payment.cs
Payment form and payment schedule batch related changes done
=> Payment form and payment schedule batch related changes done

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantageSvc/Model/MVA009Batch.cs
fixed account date issue and applied check
=> fixed account date issue and applied check

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js, ViennaAdvantageSvc/Model/MVA009Batch.cs, ViennaAdvantageSvc/Model/X_VA009_Batch.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs, ViennaAdvantageSvc/Process/VA009_Generate_Payment.cs
=> Currency Name correction

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineForm.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs
=> commenting

ViennaAdvantageSvc/Process/VA009_Generate_Payment.cs
=> Removed amount conversion

ViennaAdvantageSvc/Process/VA009_CreateBatchLineForm.cs
set discount amount if same currency when based on rule selected
=> set discount amount if same currency

ViennaAdvantage/Areas/VA009/Controllers/PaymentController.cs, ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js, ViennaAdvantageSvc/Process/VA009_CreateBatchLineForm.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs, ViennaAdvantageSvc/Process/VA009_Generate_Payment.cs
1.In case payment in drafted stage from Batch-- then for Invoice Is-paid checkbox should not be true
2.On based on selection, for currency type-- de-active currency types also coming (sandbox)
3.For order--currency rate type picking from header and discount not updating correct in batch (sandbox)-- check 
4.For based on rule, after creation of batch-- message should be proper-- done 
5.Invoice created in Store and in Payment form-- Hq selected. PSB created in Hq. Later dlt batch lines and used Generate line. Invoice come in dropdown but error come batch line not created.
7. On Bank to Bank Transfer system should show the document type as per Bank account Organization not as per Organization.
=> handle Payment form and payment schedule batch issues

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs, ViennaAdvantageSvc/Process/VA009_Generate_Payment.cs
line and payment process : handle messgaes
=> payment form : handle From and to date format

ViennaAdvantage/Areas/VA009/Scripts/model/callouts.js
Set override auto check based on autocheck control and checkno
=> Set override auto check based on autocheck control and checkno

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Reset design of control when open from cheque receivable
=> Reset design of control when open from cheque receivable

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Removed outer scroll bar on dialogs
=> Removed outer scroll bar on dialogs

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
=> fixed scroll issues

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
search amount in slovaian format, replaced comma with dot if format is not dot
=> search amount in slovaian format

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Handle amount search according to culture in searchtext field
=> Handle amount search according to culture in searchtext field

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Fixed scroll issue on left search panel
=> Fixed scroll issue on left search panel

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
increased height of cash and payment selection popups
=> increased height of cash and payment selection popups

ViennaAdvantage/Areas/VA009/Models/PayModel.cs, ViennaAdvantage/Areas/VA009/Scripts/model/callouts.js
Get Due amount (GrandTotal-DueAmt) based on orderid when no VA009_OrderPaySchedule_ID found
GrandTotal-Get sum of DueAmt of OrderPaySchedule which are paid
=> Set due amount when  VA009_OrderPaySchedule_ID not found

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Fixed scroll issue ,Reset paging like no of pages
=> Fixed scroll issue ,Reset paging like no of pages

ViennaAdvantage/ViennaAdvantage.csproj
=> project file

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs
Set date account after statement date
=> Set date account after statement date

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js, ViennaAdvantageSvc/Process/VA009_CreateBatchLineForm.cs
added account date on batch schedule payment
=> added account date on batch schedule payment

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
=> while Order selection getting wrong check amount issue fixed

ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
Devops Id: 2247 Handeled amount issue when user unselect the record from let pannel
=> Devops Id:2246 Handeled the Issue of record mismatch

ViennaAdvantage/ViennaAdvantage.csproj, ViennaAdvantageSvc/Process/VA009_GeneratePaymentCheckStub.cs
=> Payment Amendment

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js, ViennaAdvantage/Areas/VA009/Scripts/model/callouts.js, ViennaAdvantageSvc/Process/VA009_CreateBatchLineForm.cs, ViennaAdvantageSvc/Process/VA009_CreateBatchLineProcess.cs
[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_VAPaymentManagement(VA009)_Above_2.1.14.0.docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAPaymentManagement(VA009)_Above_2.1.14.0.docx?d=w470bdc249ed145a59f17a54de09e3499&csf=1&web=1&e=YFwM2O)?d=w470bdc249ed145a59f17a54de09e3499&csf=1&web=1&e=YFwM2O)
[5620](http://130.61.149.181/ViennaAdvantage/_search?text=5620&type=workitem&lp=custom-Collection)
=> BugID 5620 Handled dicount amount based on dicount dates if applicable

ViennaAdvantage/Areas/VA009/Models/PaymentModel.cs, ViennaAdvantage/Areas/VA009/Scripts/apps/forms/PaymentForm.js
1)Calculate discount when user split schedule
2)subtract value of writeoff and discount when overunder value is greater than 0. 3)commented code which is not required.
[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_VAPaymentManagement(VA009)_Above_2.1.14.0(1).docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAPaymentManagement(VA009)_Above_2.1.14.0(1).docx?d=wd11f1333ac964da697fcec265bba977e&csf=1&web=1&e=u400ul)?d=wd11f1333ac964da697fcec265bba977e&csf=1&web=1&e=u400ul)
=> Handled Below points-
